#服务器端口
server:
  port: 7500

#数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.1.3/uupush?characterEncoding=utf-8&useSSL=false
    username: root
    password: "@Dccshop2017"
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      connection-timeout: 60000
      minimum-idle: 5
      idle-timeout: 60000

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: 192.168.1.5  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password:        # Redis服务器连接密码（默认为空）
    timeout: 0       # 连接超时时间（毫秒）
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0    # 连接池中的最小空闲连接

  rabbitmq:
    host: 192.168.1.3
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /       
            
feign:
  hystrix:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true   